---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3014610573-diY7XIaOXw1QIbUYLOcHN1qCE7Q2O67u47r1vxu
:access_token_secret: EgLNcELzgxVZrO7yhFvDTL5LRZNwT3p8OkxLOapdKTGEy
